home/urls.py
from django.urls import path, include
from . import views

app_name = 'recipes'

urlpatterns = [
    path('',views.home, name="home"),
    path('recipes/<int:id>/', views.recipe, name="recipe")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from home import urls as h
from django.conf.urls.static import static
from django.conf import settings

# h = home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(h))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)

    descripition = models.CharField(max_length=165)

    slug = models.SlugField()

    preparation_time = models.IntegerField()

    preparation_time_unit = models.CharField(max_length=65)

    serving = models.IntegerField()

    serving_unit = models.CharField(max_length=65)

    preparation_steps = models.TextField()

    preparation_steps_is_html = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    update_at = models.DateTimeField(auto_now=True)

    is_published = models.BooleanField(default=False)

    cover = models.ImageField(upload_to='home/covers/%Y/%m/%d')

    category = models.ForeignKey(Category,on_delete=models.SET_NULL, null=True)

    author = models.ForeignKey(User,on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render
from util.recipes.factory import make_recipe

# Create your views here.
def home(request):

    context = {
        'recipes': [make_recipe() for _ in range(10)],
    }

    return render(request,'home/pages/home.html',context=context)


def recipe(request,id):

    context = {
        'recipe': make_recipe(),
        'is_detail_page':True
    }

    return render(request,'home/pages/recipe-view.html', context=context)

home/templates/home/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}Home

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'home/partials/recipes.html' %}              
    {% endfor %}
</div>
{% endblock content %}

home/templates/home/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}Alterar | {% endblock title %}Alterar | 

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'home/partials/recipes.html' %}    
    </div>
{% endblock content %}

home/templates/home/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Luiz Zomer</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

home/templates/home/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'home/css/style.css'  %}">
<link rel="stylesheet" href="{% static 'global/css/global.css'  %}">

home/templates/home/partials/header.html
<header class="home-header">
    <div class="header-container container">
        <a class="main-logo" href="{% url 'recipes:home' %}">
            <h1>
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </h1>
        </a>
    </div>
</header>

home/templates/home/partials/recipes.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href=" {% url 'recipes:recipe' recipe.id %} ">
            <img src="{{recipe.cover.url}}" alt="temporario">
        </a>
    </div>

    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <h2 class="recipe-title">{{recipe.title}}</h2>
        </a>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {{recipe.author.first_name}} {{recipe.author.last_name}}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at | date:"d/m/Y" }} ás {{ recipe.created_at | date:"H:i" }}
        </span>
        <span class="recipe-author-item">
            <a href="/recipes/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>


    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {{recipe.preparation_steps | linebreaksbr }}
        </div>
    {% endif %}
</div>

home/templates/home/partials/search.html
<div class="search-container">
    <div class="container"> 
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass" ></i></button>
        </form>
    </div>
</div>